global using GOCAP.Common;
global using GOCAP.Repository.Intention;
global using GOCAP.Services.Intention;
global using GOCAP.Domain;
global using GOCAP.Repository;
global using Microsoft.Extensions.Logging;
global using System.Linq.Expressions;
global using GOCAP.ExternalServices;
global using System.Text.Json;