namespace GOCAP.Tests.Integration;

public abstract class ApiControllerTestsBase : IClassFixture<WebApplicationFactory<Api.Program>>
{
    protected readonly string _accessToken = "eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJwaWN0dXJlIjoie1wiVXJsXCI6XCJodHRwczovL3N0b3JhZ2UuZGVyYXBpLmlvLnZuL2NhcGNhcC9nb2NhcC9hZDdhM2M5ZC0zMWU4LTQwYjQtODgxNy00NzhjZGUzODRmMWMtMjAyNTAzMTAxODA5LUltYWdlLnBuZ1wiLFwiVHlwZVwiOjEsXCJUaHVtYm5haWxVcmxcIjpudWxsfSIsInVuaXF1ZV9uYW1lIjoiR8OidSBHw6J1IiwiZW1haWwiOiJicmlnaHRzdW50bmMyMDAzQGdtYWlsLmNvbSIsImlkIjoiOWQ4NWU0OWMtYjZiNi00OWRlLTg2Y2EtNTJlYzExMzZlY2ZlIiwicm9sZSI6IlVzZXIiLCJuYmYiOjE3NDQxMzE3NTYsImV4cCI6MTc0NDEzODk1NiwiaWF0IjoxNzQ0MTMxNzU2LCJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo3MDM1IiwiYXVkIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NzAzNSJ9.dDAWm7RL9VJhjuT5k8p9rLZZDos6sUJT4ONMLUwk3u5OaGl8N-JKBIDD2IZQnFfDwwhglHSRjIyPpaE50334fw";
}
